spring:
  application:
    name: t1-java-demo
  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_demo"
    username: bestuser
    password: bestuser
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

logging:
  level:
    ROOT: INFO
#    org.apache.kafka: INFO
#    org.hibernate.SQL: INFO

t1:
  scan-path: ru.t1.java.demo
  kafka:
    count:
      time: 300000
      transactions: 5
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    session:
      timeout:
        ms: 30000
    max:
      partition:
        fetch:
          bytes: 300000
      poll:
        records: 1
        interval:
          ms: 300000
    heartbeat:
      interval:
        ms: 3000
    consumer:
      transaction:
        accept:
          group-id: t1-demo-transaction-accept
          max.poll.records: 10
    producer:
      enable: true
    topic:
      transaction_accept: t1_demo_transaction_accept
      transaction_result: t1_demo_transaction_result
    listener:
      poll-timeout: 1000